var R=require("../chunks/ssr/[turbopack]_runtime.js")("server/app/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__01sg8zj._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_0.ccysc.js")
R.c("server/chunks/ssr/[root-of-the-server]__046ob_5._.js")
R.c("server/chunks/ssr/[root-of-the-server]__098zro9._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0n5.i5o._.js")
R.c("server/chunks/ssr/node_modules_0_ce7g1._.js")
R.c("server/chunks/ssr/app_layout_tsx_13yf0ls._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0inhx6q._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0ghu-f7.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/[root-of-the-server]__0s7k_9h._.js")
R.c("server/chunks/ssr/[root-of-the-server]__09ngawv._.js")
R.m(68648)
module.exports=R.m(68648).exports
