// Storage abstraction for ledger files. Implementations: filesystem (local
// dev) and Vercel Blob (production). The server actions depend only on this
// interface, so swapping backends is a one-line change in index.ts.

export interface StoredEntity {
  id: string;
  name: string;
  beancount: string;
}

export interface LedgerStore {
  listEntities(): Promise<{ id: string; name: string }[]>;
  loadEntity(id: string): Promise<StoredEntity | null>;
  saveEntity(id: string, beancount: string): Promise<void>;
  createEntity(id: string, name: string): Promise<StoredEntity>;
  deleteEntity(id: string): Promise<void>;
}

/** Extract the title from a ledger's `option "title"`. */
export function titleOf(text: string, fallback: string): string {
  const m = text.match(/option\s+"title"\s+"([^"]*)"/);
  return m ? m[1] : fallback;
}

/** Sanitize an id to a safe slug (also guards against path traversal). */
export function safeId(id: string): string {
  return id.replace(/[^a-zA-Z0-9_-]/g, "");
}

/** The seed ledger written on first run when the store is empty. */
export const SAMPLE_ID = "sample-company";

// 3-year sample services-firm ledger (~9k transactions), generated by
// scripts/gen-sample.mts into sample-data.ts (so it's reliably bundled on
// Vercel). Re-run that script to regenerate.
export { SAMPLE_LEDGER } from "./sample-data";
